---
driver:
  name: dokken
  chef_version: latest
  privileged: true
  volumes: '/var/lib/docker'

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:

- name: amazonlinux
  driver:
    image: amazonlinux:latest
    intermediate_instructions:
      - RUN yum -y install upstart procps util-linux
    pid_one_command: /sbin/init
    
suites:
  - name: default
    run_list:
      - recipe[chef_repo_server]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      chef_repo_server:
        common_name: '127.0.0.1'
